### ISSUE TITLE
MapTest usage of CustomData

### ISSUE THREAD

**Issue by samdark** [yiisoft/hydrator#17]
Usage of `CustomData` attribute to fill data in `MapTest` makes it harder to read compared to passing data array directly. Would it make sense to do it in a simple way?

**Comment by vjik** [comment]
Usage `CustomData`:
- Open `MapClass`
- View data in `CustomData` attribute
- View mapping in `Map` attribute
- Open `MapTest`
- View compared value

**Comment by vjik** [comment]
In any case, we need data from `Map` attribute.

Usage `CustomData`:
- Open `MapClass`
- View data in `CustomData` attribute
- View mapping in `Map` attribute
- Open `MapTest`
- View compared value

Usage simple way:
- Open `MapTest`
- View data in `create()` method
- Open `MapClass`
- View mapping in `Map` attribute 
- Open `MapTest`
- View compared value

Seems, usage `CustomData` is a bit easier... In simple way we should make more jumps beetwen files.

**Comment by samdark** [comment]
The problem is that it is not how it is done in real code. It is very unlikely that someone will assign values with something like `CustomData`.
