### ISSUE TITLE
Rename `SkipTypeCastException`

### ISSUE THREAD

**Issue by vjik** [yiisoft/hydrator#20]
To `NotTypeCastedException` for consistency with `NotResolvedException`

**Comment by samdark** [comment]
Is the exception thrown when nothing was type-casted or when you want to skip type-casting?

**Comment by vjik** [comment]
> Is the exception thrown when nothing was type-casted or when you want to skip type-casting?

When type caster don't can type cast value. I mean yes, "want to skip type-casting".

This exception never throws in userland. Hydrator always catch it:

https://github.com/yiisoft/hydrator/blob/227f0d40387fe1022369b0798a5aff280065422c/src/Hydrator.php#L167

https://github.com/yiisoft/hydrator/blob/227f0d40387fe1022369b0798a5aff280065422c/src/Hydrator.php#L113

**Comment by samdark** [comment]
Then:

1. It's not great to use exceptions to control execution flow overall.
2. `SkipTypeCastException` as a name is good for the current use-case.

**Comment by vjik** [comment]
> 1. It's not great to use exceptions to control execution flow overall.

I know one another way — use result object (`return new Result($typeCastedValue)` or `return (new Result())->skipTypeCast()`). But, seems, it's more difficult. Is there any other approach?

**Comment by samdark** [comment]
No. Either returning results or exceptions.

https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why

**Comment by vjik** [comment]
I think, better refactor code and use result object with private constructor:

```php
final class TypeCastResult
{
    private function __construct(
        private bool $isCasted,
        private mixed $value = null,
    ) {
    }

    public static function success(mixed $value): self
    {
        return new self(true, $value);
    }

    public static function fail(): self
    {
        return new self(false);
    }

    public function isCasted(): bool
    {
        return $this->isCasted;
    }

    public function getValue(): mixed
    {
        return $this->value;
    }
}
```

And interface will be:

```php
interface TypeCasterInterface
{
    public function cast(mixed $value, ?ReflectionType $type): TypeCastResult;
}
```

It's look fine. What do you think?

Examples of usage:

```php
return TypeCastResult::success($typeCastedValue);
return TypeCastResult::fail();
```
