### ISSUE TITLE
Add support for custom path separator like in validator

### ISSUE THREAD

**Issue by arogachev** [yiisoft/hydrator#3]
https://github.com/yiisoft/hydrator/blob/e90ebf0b5f35c64ae8b05a919600e94d8f278fe3/src/Context.php#LL56C21-L56C21

**Comment by vjik** [comment]
It's not need, because dot don't can be part of key. Keys is class properties always. Class properties don't can contain dots.

**Comment by arogachev** [comment]
What about nested structures and mapping?

**Comment by vjik** [comment]
> What about nested structures and mapping? Here for example:

Nested strctures is object properties always. Object property name contain not dots.

**Comment by arogachev** [comment]
Got it, thanks for the explanation. Closing then.
